#@include file-fluent.conf

apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: fluentd
data:
  fluent.conf: |-
    ################################################################
    # This source gets all logs from local docker host
    #@include pods-kind-fluent.conf
    #@include pods-fluent.conf
    #@include file-fluent.conf
    #@include elastic-fluent.conf
    @include mongo-fluent.conf
  file-fluent.conf: |-
    <match **>
      @type file
      path /tmp/file-test.log
    </match>
  mongo-fluent.conf: |-
    <match **>
      @type mongo
      host "#{ENV['FLUENT_ELASTICSEARCH_HOST'] || 'mongo'}"
      port "#{ENV['FLUENT_ELASTICSEARCH_PORT'] || '27019'}"
      user root
      password QNn7oWyqMK
      index_name fluentd-k8s
      type_name fluentd
    </match>